[tool.black]
line-length = 79
target-version = ['py37']
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude  ='''(manage.py|settings.py|asgi.py|wsgi.py|urls.py|migrations/|tests/*)'''
